= Preparation

Work through these steps before digging into a specific error. They set up the app and the debugging environment so the root cause of an issue is easier to identify.

[#ui-compatibility]
== UI compatibility

Make sure that the app is compatible as documented in xref:documentation:onecx-portal-ui-libs:onecx-compatibility.adoc[OneCX UI Compatibility].

[#improve-debugging-experience]
== Improve the debugging experience

To understand the root cause of issues, it is recommended to enable source maps in the application and shell during development. For more information on how to enable source maps, see xref:documentation:docs-guides-ui:ui-additional/enable-source-maps.adoc[Enable source maps guide].

[#disable-minified-build]
== Disable the minified build

To better debug your app, disable the minified build.

* In your `project.json` or `angular.json` file, set `"optimization"` to `false` in the build options. This disables minification of the build files for all configurations (production, development).

.Example for all builds
[source,json]
----
{
...
"targets": {
    ...
    "build": {
        ...
        "options": {
            "optimization": false,
            ...
        }
        ...
    }
    ...
  }
}
...
----

* If you want to disable minification only for a specific build, set `"optimization"` to `false` in the respective configuration:

.Example for production build
[source,json]
----
{
...
"targets": {
    ...
    "build": {
        ...
        "configurations": {
            "production": {
                "optimization": false,
                ...
            }
            ...
        }
        ...
    }
    ...
  }
}
...
----

* If you get an error like `Error: bundle initial exceeded maximum budget. Budget 1.05 MB was not met by 267.90 kB with a total of 1.32 MB.`, increase the budget in the `budgets` section of your `project.json` or `angular.json` file.

.Example budgets section
[source,json]
----
{
...
"targets": {
    ...
    "build": {
        ...
        "configurations": {
            "production": {
                "optimization": false,
                "budgets": [
                    {
                      ...
                      "maximumError": "1.5mb"
                    },
                    ...
                ]
                ...
            }
            ...
        }
        ...
    }
    ...
  }
}
...
----

You can see the difference between a minified and a non-minified code snippet in the DevTools Sources tab.

.Example code snippet in the DevTools Sources tab
[cols="1a,1a",options="header"]
|===
| minified
| non-minified

|
[source,javascript]
----
...
 ), (0,
        x.on)(k.searchButtonClicked, (t, {searchCriteria: s}) => ({
            ...t,
            criteria: s
        })), (0,
        x.on)(k.resetButtonClicked, t => ({
            ...t,
            criteria: {}
        })), (0,
        x.on)(k.tenantSearchResultsReceived, (t, {results: s}) => ({
            ...t,
            results: s
        })), (0,

...
----

|
[source,javascript]
----
...
search(formValue) {
      const searchCriteria = Object.entries(formValue.getRawValue())
        .reduce((acc, [key, value]) => ({
        ...acc,
        [key]: this.isVisible(key) ?
          (0,_shared_utils_isValidDate_utils__WEBPACK_IMPORTED_MODULE_5__
            .isValidDate)(value) ?
            new Date(Date.UTC(value.getFullYear(), value.getMonth(),
              value.getDate(), value.getHours(), value.getMinutes(),
              value.getSeconds())) :
            value {vbar}{vbar} null : null
      }), {});
      this.store.dispatch(_tenant_search_actions__WEBPACK_IMPORTED_MODULE_6__
        .TenantSearchActions.searchButtonClicked({
        searchCriteria
      }));
    }
    resetSearch() {
      this.store.dispatch(_tenant_search_actions__WEBPACK_IMPORTED_MODULE_6__
        .TenantSearchActions.resetButtonClicked());
    }
...
----
|===

You can also see the difference between a minified and a non-minified `NullInjectorError` message in the console.

.Example `NullInjectorError` (non-minified in the app)
[cols="1a,1a",options="header"]
|===
| minified
| non-minified

|
----
ERROR NullInjectorError: R3InjectorError[PortalDialogService -> i -> i -> i]:
  NullInjectorError: No provider for i!
----
|
----
ERROR NullInjectorError: R3InjectorError[i -> i -> i -> i]:
  NullInjectorError: No provider for i!
----
|===

If you are still seeing names like `i` in the non-minified error message, disable the minified build for the shell locally as well:

* Clone the shell repository `https://github.com/onecx/onecx-shell-ui`.
* Run `npm install`.
* Set `"optimization"` to `false` in the `project.json` file of the shell.
* Depending on your app's Angular version, set the `"optimization"` option in the corresponding `pre_loaders/angular-<version>/project.json` file. For example, for Angular 18 use `pre_loaders/angular-18/project.json`.
* To start the shell locally, use xref:documentation:onecx-docs-start:first-app/image_build_automatic.adoc[Automatic Image Build], which builds from your local source code each time you run `docker compose`, or xref:documentation:onecx-docs-start:first-app/image_build_manual.adoc#manual-image-build[Manual Image Build] for manual image building.

.Example `NullInjectorError` (non-minified in the app and the shell)
[cols="1a,1a",options="header"]
|===
| app non-minified
| app + shell non-minified

|
----
ERROR NullInjectorError: R3InjectorError[PortalDialogService -> i -> i -> i]:
  NullInjectorError: No provider for i!
----
|
----
ERROR NullInjectorError: R3InjectorError[PortalDialogService -> DialogService -> DialogService -> DialogService]:
  NullInjectorError: No provider for DialogService!
----
|===
